### PR TITLE
Use Object.keys() instead of for..in construct

### PR DESCRIPTION
**Pull request by FredyC**
As per documentation...

> The Object.keys() method returns an array of a given object's own enumerable properties, in the same order as that provided by a for...in loop (the difference being that a for-in loop enumerates **properties in the prototype chain** as well).

I run into this issue in IE11 where I have to polyfill `Array.prototype.includes`. This is then enumerated as well and causing weird issues.

Note that `Object.keys` works for arrays as well, so nothing is broken by this change.

### CODE REVIEW

**Comment by FredyC** [comment]
@manuelbieh Can you please have a look at this?

**Comment by FredyC** [comment]
ping @manuelbieh

**Comment by FredyC** [comment]
Not sure why this wasn't merged after approval. I've fixed conflicts.

**Comment by manuelbieh** [comment]
Sorry, I'm currently working on Geolib v3 behind the scenes so v2 has had a pretty low priority for me recently. If you are interested in helping me maintaining the lib I can add you as contributor. Just drop me a line!

**Comment by FredyC** [comment]
No thank you, it was a one time I needed your lib and now I just wanted to clear out my list of pending PRs :)

**Comment by manuelbieh** [comment]
Ok ;)

**Pull request merged**
