### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by chucre**
Update documentation to add precision in geolib.getDistance and add method geolib.isPointInLine.

### CODE REVIEW

**Comment by chucre** [comment]
@manuelbieh hold on this PR. I will check and update all methods, if necessary.

**Comment by chucre** [comment]
I found the fallow methods undocumented:
alias:
getKeys
getLat
getLon
isInside
withinRadius
getDirection

methods:
validate
getDistanceSimple
getBounds
getBoundsOfDistance
preparePolygonForIsPointInsideOptimized
isPointInsideWithPreparedPolygon
getRhumbLineBearing
getBearing
getCompassDirection
decimal2sexagesimal
isDecimal
isSexagesimal
round

Should I add reference in README.md to create another file? And if yes, should I move all other documented methods to same file? I Think we could create a file: docs/API.md

**Comment by manuelbieh** [comment]
Oops, now I merged it.

docs/API.md sounds like a good idea since the number of methods is constantly growing. Unfortunately, to be honest, I don't know how every of the methods mentioned above works. `getBoundsOfDistance`, `preparePolygonForIsPointInsideOptimized` and `isPointInsideWithPreparedPolygon` for example were pull requests which I merged without completely understanding how they work or what they do exactly. 

I understood just enough to decide that they sound like useful extensions ;)

**Comment by chucre** [comment]
O will move documentation to that file and checkout how theses two methods works, if I can't I will try contact with original authors

**Pull request merged**
