### PR TITLE
Speedup twice orderByDistance

### PR DESCRIPTION
**Pull request by pawelpalka81**
Speed up 'orderByDistance' function, tested on 10k spots :
from Requests per second:    3.16 [#/sec] 
to Requests per second:    5.39 [#/sec]

### CODE REVIEW

**Comment by manuelbieh** [comment]
I was doing `Object.create` for a some good reason here :wink:

First of all - the main reason is your version _modifies_ existing arrays of coord objects while the existing solution creates a _copy_ of each coordinate, without modifying existing coordinate objects, which _might_ otherwise lead to some unwanted side effects.

Second reason is, `coords[coord]` is not necessarily a coordinate *object*. I allowed `[longitude, latitude]` as coordinate format some time ago to make working with GeoJSON coordinates easier. So setting a distance and a key property on an array is technically possible but not the most elegant solution :simple_smile:

**Comment by pawelpalka81** [comment]
Thx for you super fast response. You have right! but maybe this speed up is worth is risk. 
Adiitionaly this risk can be mitigate by let`s say more uniq name for key and distance eg: __key or __distance

**Comment by manuelbieh** [comment]
You might be right. I'm currently working on Geolib v3. Maybe I will introduce it as breaking change. Definitely worth a try. Thanks!

**Comment by pawelpalka81** [comment]
Also consider use a https://github.com/mourner/rbush-knn or implement own. 
It give such big performance improvement for my case 
up to Requests per second: 700.10 [#/sec]

**Comment by manuelbieh** [comment]
This function will be rewritten from the ground up in v3 which I will release shorty. So I'm closing this one!

**Pull request closed without merging**
