### PR TITLE
fix precision

### PR DESCRIPTION
**Pull request by sylvainlap**
precision is now taken into account

### CODE REVIEW

**Comment by sylvainlap** [comment]
The test that fails is due to isPointInLine(), that I did not change.

**Comment by ptz0n** [comment]
The function `isPointInLine` uses `getDistance`, hence the failed test. Please update to make sure it passes.

**Comment by sylvainlap** [comment]
The test fails because of this:
```
1113194.908 + 556597.454 = 1669792.3620000002
```

o_O

I don't know why JS decides to add 0.0000000002 to the result... I'll try to fix that.

**Comment by sylvainlap** [comment]
fixed !

**Comment by sylvainlap** [comment]
Hi @ptz0n.

Are you ok to merge this PR ?

**Comment by manuelbieh** [comment]
Thanks!

The issue you had is described here:
http://stackoverflow.com/questions/11695618/dealing-with-float-precision-in-javascript

**Pull request merged**
